# Generated by Django 3.0.1 on 2020-05-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0002_auto_20200503_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='in_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
