# Generated by Django 3.0.1 on 2020-10-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0004_auto_20201018_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.TextField(choices=[('Added', 'Addition'), ('Deleted', 'Deletion')]),
        ),
    ]
