# Generated by Django 3.0.1 on 2020-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0004_customer_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='exp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='mfg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
