# Generated by Django 3.0.1 on 2020-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0005_auto_20200510_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='process',
            field=models.BooleanField(default=False),
        ),
    ]
