# Generated by Django 3.0.1 on 2020-05-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0006_damage_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='best_before',
        ),
    ]
