# Generated by Django 3.0.1 on 2020-05-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0008_auto_20200515_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='mfg',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='process',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='quantity',
        ),
    ]
