# Generated by Django 3.0.1 on 2020-05-18 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0009_auto_20200516_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('mfg', models.DateField()),
                ('exp', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouseapp.Customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Damage',
        ),
    ]
